language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install librrd-dev
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install python-rrdtool --use-mirrors
script: python manage.py test timegraph
