# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timegraph', '0003_auto_20170912_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='cache_timeout',
            field=models.IntegerField(default=0, verbose_name=b'Timeout'),
        ),
    ]
